# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

codecov:
  notify:
    after_n_builds: 1
    wait_for_ci: yes
  require_ci_to_pass: yes

# Coverage configuration
# ----------------------
coverage:
  status:
    project: yes
    patch: yes
    changes: no

  range: 70..90     # First number represents red, and second represents green
                    # (default is 70..100)
  round: down       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5



# Pull request comments:
# ----------------------
comment:
  layout: reach, diff, flags, files, footer
  behavior: default
  require_changes: true
