name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        export PATH=/usr/bin:$PATH
        sudo apt-get update -q
        sudo apt-get install libdbus-1-dev
        sudo apt-get install libdiscid0
        sudo apt-get install --yes gstreamer1.0-alsa gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-libav
        sudo apt-get install -y libgirepository1.0-dev libcairo2-dev gir1.2-gtk-3.0 gobject-introspection python3-gi python3-gi-cairo gir1.2-gtk-3.0 python3-gst-1.0
        sudo apt-get install -y xvfb
        sudo apt-get install dbus-x11
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
        export $(dbus-launch)
    - name: Install python dependencies
      # mediadb backend requires tagpy and it does not provide binaries for Python
      # versions greater than 3.9, which can cause build failures. So we only install
      # mediadb dependencies for the python version that we use for our codecov reports.
      # Note that the mediadb tests will also be skipped if the dependencies are not installed.
      run: |
        python -m pip install --upgrade pip
        if [[ ${{ matrix.python-version }} == "3.7" ]]; then
          python -m pip install .[dev,mediadb]
        else
          python -m pip install .[dev]
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics coherence/ tests/
        # exit-zero treats all errors as warnings
        flake8 --count --exit-zero --ignore=E402,W503 --max-complexity=10 --max-line-length=80 --statistics coherence/ tests/
    - name: Lint with pylint
      run: |
        pylint -E coherence --rcfile=.pylintrc
    - name: Unit tests with nose
      run: |
        nosetests --config=.noserc
    # The following steps will only be run for python 3.7
    - name: Upload coverage report to Codecov
      if: matrix.python-version == '3.7'
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        files: ./coverage.xml
        flags: unittest
        name: Cohen3
        fail_ci_if_error: true
    - name: Build sphinx docs
      if: matrix.python-version == '3.7'
      run: |
        pip install travis-sphinx
        pip install sphinx-rtd-theme
        travis-sphinx build -n --source=docs
    # We only deploy docs when we merging to master branch
    - name: Deploy sphinx docs
      if: matrix.python-version == '3.7' && github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        travis-sphinx deploy
